# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ymvkne2RaZRIU5KFiCWJ0b8ezQ4LSqsM
"""

from keras.datasets import cifar10
import matplotlib.pyplot as plt
import numpy as np

(x_train,y_train),(x_test,y_test)=cifar10.load_data()

label_data=[
    "airplane",#飛行機
    "automobile",#自動車
    "bird",#鳥
    "cat",#猫
    "deer", #鹿
    "dog",#犬
    "frog",#カエル
    "horse",#馬
    "ship",#船
    "truck"#トラック
]

plt.figure(figsize=(10,10))
for i in range(25):
    rand_num=np.random.randint(0,50000)
    cifar_img=plt.subplot(5,5,i+1)
    plt.imshow(x_train[rand_num])
    #x軸の目盛りを消す
    plt.tick_params(labelbottom='off')
    #y軸の目盛りを消す
    plt.tick_params(labelleft='off')
    #正解ラベルを表示
    label = int(y_train[rand_num])
    plt.title(label_data[label])


plt.show()
